branch: false
ignore-not-existing: true
llvm: true
output-type: lcov
ignore:
  - "/*"
  - "C:/*"
  - "../*"
  - src/main.rs
  - src/lib.rs
  - src/activity_manager.rs
  - src/filetransfer/transfer/s3/mod.rs
  - src/support.rs
  - src/system/notifications.rs
  - "src/ui/activities/*"
  - src/ui/context.rs
  - src/ui/input.rs
